// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrate/db seed/generate) uses the DIRECT (unpooled) Neon connection —
    // PgBouncer's transaction-pooling mode doesn't support the advisory locks Prisma Migrate
    // relies on. The application runtime uses DATABASE_URL (pooled) instead — see lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
